version: 2.1

orbs:
  maven: circleci/maven@1.0.3

jobs:
  publish:
    executor: java8
    steps:
      - checkout
      - run:
          name: Publish to GitHub Packages
          command: |
            exports PACKAGE_VERSION=$(git tag -l --points-at HEAD)
            mvn deploy --settings settings.xml

tag-filters:
  version-tag-only: &version-tag-filter #Only run on tag commits (not branch commits) where the tag matches the version regex e.g. 0.0.1
    filters:
      branches:
        ignore: /.*/
      tags:
        only: /^\d+\.\d+\.\d+$/

  any-tag: &always-run-filter #Run on commits either with or without a tag.
    filters:
      tags:
        only: /.*/

workflows:
  test-and-publish:
    jobs:
      - maven/test:
          <<: *always-run-filter
          matrix:
            parameters:
              executor: [java8, java11, java15]
      - publish:
          <<: *version-tag-filter
          requires:
            - maven/test-java8
            - maven/test-java11
            - maven/test-java15

executors:
  java8:
    docker:
      - image: cimg/openjdk:8.0
  java11:
    docker:
      - image: cimg/openjdk:11.0
  java15:
    docker:
      - image: cimg/openjdk:15.0

