version: 2.1

orbs:
  maven: circleci/maven@1.0.3

jobs:
  publish:
    executor: java8
    steps:
      - checkout
      - run:
          name: Publish to GitHub Packages
          command: mvn --settings settings.xml deploy

publish-filter: &publish-filter
  filters:
    # ignore any commit on any branch by default
    branches:
      ignore: /.*/
    # only act on version tags in the format 0.0.1
    tags:
      only: /^\d+\.\d+\.\d+$/

workflows:
  test-and-publish:
    jobs:
      - maven/test:
          matrix:
            parameters:
              executor: [java8, java11, java15]
      - publish:
#          <<: *publish-filter
          requires:
            - maven/test-java8
            - maven/test-java11
            - maven/test-java15

executors:
  java8:
    docker:
      - image: cimg/openjdk:8.0
  java11:
    docker:
      - image: cimg/openjdk:11.0
  java15:
    docker:
      - image: cimg/openjdk:15.0

